# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define() do

  create_table "albums", :force => true do |t|
    t.column "name", :string, :limit => 50, :default => "New Album", :null => false
  end

  create_table "photos", :force => true do |t|
    t.column "album_id", :integer,               :default => 0,          :null => false
    t.column "position", :integer,               :default => 1,          :null => false
    t.column "file",     :binary,                :default => "",         :null => false
    t.column "width",    :integer, :limit => 50, :default => 0,          :null => false
    t.column "height",   :integer, :limit => 50, :default => 0,          :null => false
    t.column "name",     :string,  :limit => 50, :default => "Untitled", :null => false
  end

  add_index "photos", ["album_id"], :name => "album_id"
  add_index "photos", ["position"], :name => "position"

end
