# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 2) do

  create_table "questions", :force => true do |t|
    t.column "quiz_id",  :integer
    t.column "position", :integer
    t.column "question", :text,    :default => "", :null => false
    t.column "answer",   :text,    :default => "", :null => false
  end

  add_index "questions", ["quiz_id"], :name => "questions_quiz_id_index"
  add_index "questions", ["position"], :name => "position"

  create_table "quizzes", :force => true do |t|
    t.column "name",       :string,                 :default => "New Quiz", :null => false
    t.column "session_id", :string,   :limit => 50, :default => "",         :null => false
    t.column "created_at", :datetime,                                       :null => false
  end

  add_index "quizzes", ["created_at"], :name => "created_at"

end
