require 'rubygems'
require 'prawn'
require "prawn/measurement_extensions"
require "prawn/security"
require "prawn/table"

Prawn::Document.generate "Myprofile.pdf" do |pdf|

pdf.fill_color "0000ff" 
pdf.stroke_color 0, 99, 95, 0

    
   
#pdf.encrypt_document :permissions => { :print_document => false }
                        # :owner_password => 'sriram'

pdf.font_size(14)
image = "#{Prawn::BASEDIR}/data/images/earth.jpeg"
pdf.text "18-06-2011",:align => :right, :size => 14, :style => :italic
pdf.text "Myprofile"
pdf.text "PROFILE", :align => :center, :size => 30, :style => :bold
pdf.image image, :at => [50,680], :width => 50
pdf.text "Name:       Sriram", :align => :center, :size => 14, :style => :bold, :color => "blue"
pdf.text "Age:            24", :align => :center, :size => 14, :style => :bold
pdf.text "qualification: MCA", :align => :center, :size => 14, :style => :bold
pdf.move_down(3)
pdf.text "This is the pdf file which is generated by using the ruby gems 'prawn' for the profile pdf", :align  => :center

=begin
data = [ ["Name", {:text => 'Sriram', :font_style => :bold, :colspan => 4 }],
 ["Address", {:text => 'Navodaya quartes', :colspan => 4 }],
 ["Landmark",{:text => 'Near power station', :colspan => 4 }],
 ["Mobile", {:text => '9866266845', :colspan => 3 }],
 ["Education", {:text => "MCA", :colspan => 4 }]

] 
pdf.table data, :border_style => :grid, #:underline_header 
:font_size => 10,
 :horizontal_padding => 6, 
:vertical_padding => 3,
:border_width => 0.7, 
:column_widths => { 0 => 130, 1 => 100, 2 => 100, 3 => 100, 4 => 80 }, 
:position => :left, 
:align => { 0 => :left, 1 => :right, 2 => :left, 3 => :right, 4 => :right } 
=end
=begin
data = [ ["Name", {:text => 'sriram', :font_style => :bold, :colspan => 4 }],
         ["Address", {:text => 'JNV quarter no :6', :colspan => 4 }], 
         ["Location",{:text => 'Kakinada', :colspan => 4 }],
         ["Mobile", {:text => "9866266845", :colspan => 3 }],
         ["Qualification", {:text => "MCA", :colspan => 4 }], 
       ] 
pdf.table data, :border_style => :grid,
:font_size => 10,
:horizontal_padding => 6,
:vertical_padding => 3, 
:border_width => 0.7, 
:column_widths => { 0 => 130, 1 => 100, 2 => 100, 3 => 100, 4 => 80 }, 
:position => :left, 
:align => { 0 => :left, 1 => :right, 2 => :left, 3 => :right, 4 => :right } 
=end
			20.times do
			pdf.start_new_page
			end
puts pdf.page_count
pdf.move_down(30)



pdf.draw_text "This is my pdf profile using prawn gem", :at => [100, 0], :size => 24, :color => "blue"

end
